---
- name: Install Applications
  hosts: osx

  vars:
      gui_apps:
          - cyberduck
          - firefox
          - google-chrome
          - iterm2
          - little-snitch
          - microsoft-office
          - visual-studio-code
          - vlc

      cli_apps:
          - dockutil
          - iperf3

  tasks:
      - name: Ensure Homebrew is up-to-date
        homebrew:
            update_homebrew: yes

      - name: Install Homebrew(CLI) Applications
        homebrew:
            name: "{{ cli_apps }}"
            state: present

      - name: Install Homebrew Cask(GUI) Applications
        homebrew_cask:
            name: "{{ item }}"
            state: present
        with_items: "{{ gui_apps }}"
