---
- name: Install Applications
  hosts: osx

  vars:
      gui_apps:
          - google-chrome
          - vlc
          - the-unarchiver
          - microsoft-office
          - firefox
          - virtualbox
          - virtualbox-extension-pack
          - little-snitch
          - iterm2
          - ableton-live-suite
          - atom
          - musicbrainz-picard
          - vmware-fusion
          - sourcetree
          - focusrite-control
          # - wireshark
          # - slack
          # - openconnect-gui

      cli_apps:
          - dockutil
          - mas
          - iperf3
          - uncrustify
          - tmux

  tasks:
      - name: Ensure Homebrew/Cask is up-to-date
        homebrew:
            state: latest
            update_homebrew: yes

      - name: start installing homebrew applications
        homebrew:
            name: "{{ cli_apps }}"
            state: present

      - name: start installing homebrew cask applications
        homebrew_cask:
            name: "{{ item }}"
            state: present
        with_items: "{{ gui_apps }}"
      - name: Brew Cleanup
        command: brew cleanup -vs


- import_playbook: dock.yml
