---
- name: Install Applications
  hosts: osx

  vars:
      gui_apps:
          - vlc
          # - the-unarchiver
          - microsoft-office
          - firefox
          # - virtualbox
          # - virtualbox-extension-pack
          - little-snitch
          - iterm2
          - ableton-live-suite
          - atom
          - musicbrainz-picard
          # - vmware-fusion
          # - fork
          - focusrite-control
          - balenaetcher
          # - cyberduck
          - tripmode
          - wireshark
          # - slack
          # - openconnect-gui
          # - db-browser-for-sqlite
          - openvpn-connect
          - gitahead

      cli_apps:
          - dockutil
          - mas
          - iperf3
          - uncrustify
          - tmux
          - gpg


  tasks:
      - name: Ensure Homebrew is up-to-date
        homebrew:
            update_homebrew: yes
            # upgrade_all: yes

      - name: start installing homebrew applications
        homebrew:
            name: "{{ cli_apps }}"
            state: present

      - name: start installing homebrew cask applications
        homebrew_cask:
            name: "{{ item }}"
            state: present
        with_items: "{{ gui_apps }}"

      - name: Brew Cleanup
        command: brew cleanup -vs


- import_playbook: dock.yml
